### ISSUE TITLE
Creating directory structure for data and script default folder

### ISSUE THREAD

**Issue by sgauravm** [UBC-MDS/DMC_Portuguese_Group_402#8]
For milestone 1 we need to create a directory structure for the repo, The script should go in src folder and the data folder can have raw and clean folders for the data

**Comment by KarlosMuradyan** [comment]
Now the script to download and extract data by default puts all the data into ./data folder. Therefore, if we put that script into ./src folder, the data will be downloaded and extracted in ./src/data folder.

Did the milestone1 explicitly require the script to be in the `./src` folder? In some real projects, the script to get the data is located in the main directory not in the `./src`

**Comment by fsywang** [comment]
milestone1 did require the script to be in some folder: "Note - this script should live in an appropriately named sub-directory of your public GitHub.com repo." 

I think if we use`../data`, it can be downloaded in a data folder outside of `src` since `..` will change to the parent working directory

**Comment by KarlosMuradyan** [comment]
Yes, it will solve the problem
